name: Terraform Execution

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Storing manifests in GitHub
      uses: actions/upload-artifact@v3
      with:
       name: terraformArtifacts
       path: terraform/*
        
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Downloading manifests from GitHub
      uses: actions/download-artifact@v3
      with:
       name: terraformArtifacts

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: 'ASIASLMTFG4QIUX52PUH'
        aws-secret-access-key: '61MP6pWfJN5V3rhNYWwNwyUlcFefHxPEbY/KTcz6'
        aws-session-token: 'FwoGZXIvYXdzEKT//////////wEaDLdDt3vPscqK5fYbXSK8AdrqcS+fVfGAokkGJu2eRBpcERhdSCGKILvGORTFO9wIDozEHtbGiHY1LhnoPsEub0YcheAgotQK7kMFVfWFrGxT1kS04Cuu7Q+wOX0CihWm36pNhKvbAxr+1eTjr80R6epnw8jCTSvDPcS4qVPdWlCL3X3F7CUH9IgXQuAYC1tzVmy9WT8LSemAI9DB7J7ME69HVUyPR+XVbtp6xnJSE7c/5dvL5NnkNnJgN6AaVkKMg/zTj1sgeRKDn9MgKOeU0KgGMi0fvq7eYiqYndAGxvXOCxtiWIoS4FQyMc/GO6ijb0FyNuR+AdjbQfbP5G/smYU='

    
    - name: Validate AWS Credentials working or not
      run: |
        aws sts get-caller-identity

    - name: Restore cached Primes
      id: cache-primes-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          terraform.tfstate*
        key: ${{ runner.os }}-state
        
    - name: Execute terraform scripts to launch S3 bucket
      run: |
        terraform init
        terraform apply --auto-approve
        
    - name: Cache state files
      id: cache-state
      uses: actions/cache@v3
      with:
        path: |
          terraform.tfstate*
        key: ${{ runner.os }}-state        
